# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 30ae3591ad00e71f78265108771a308713a48c5902f2e0834f1ec424d6af3bffa8a23d143dd762cad1a8b065175998cea96c489d9fc8147de1089f1f18afd42d
  dbserver_import: localhost
  username_import: root
  password_import:
  databasename_import: catalogi_catalogindustry
  stripe_api_key: sk_test_92GSNi6TyUwRHQeiogjSX5hW


# stripe demo card
  number: '5555555555554444'
  month: '12'
  year: '2020'
  cvv: 123
  name_on_card: 'Demo name'

  recaptcha_site_key: 6LeHJ18UAAAAAGmKe1wzy4U-DHdBQl5e7OsH5Zbs
 # Added line
  recaptcha_secret_key: 6LeHJ18UAAAAAEGofuiOZSyr_NU-VgRly195cdCO
 # Added line

test:
  domain_name: example.com
  secret_key_base: 2c91545908855968aaaa30078dd7e2b5c97a76adda8f5193b039e38331d4d533cbe83b42a8b835e887330f8d0fc9c627225837526c368f13d2c3481e381e9eb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_api_key: sk_live_gBn3kszs27j0VFxwzGQerc2u

  recaptcha_site_key: 6LeHJ18UAAAAAGmKe1wzy4U-DHdBQl5e7OsH5Zbs
 # Added line
  recaptcha_secret_key: 6LeHJ18UAAAAAEGofuiOZSyr_NU-VgRly195cdCO
 # Added line

staging:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_api_key: sk_test_92GSNi6TyUwRHQeiogjSX5hW

  recaptcha_site_key: 6LeHJ18UAAAAAGmKe1wzy4U-DHdBQl5e7OsH5Zbs
 # Added line
  recaptcha_secret_key: 6LeHJ18UAAAAAEGofuiOZSyr_NU-VgRly195cdCO
 # Added line
